### ISSUE TITLE
Missing conditional build macros

### ISSUE THREAD

**Issue by FrostbyteGR** [Icinga/rpm-icinga2#11]
Currently we're not able to instruct `rpmbuild` to include or omit features described in the [CMake Variables section](https://icinga.com/docs/icinga2/latest/doc/21-development/#cmake-variables) of the development documentation.

For example I might want to disable `UNITY_BUILD`, while issuing `rpmbuild --rebuild` directly to the SRPM, instead of extracting it and then issuing `rpmbuild -bb` on the modified spec file.

Related PR #12, please review.

Thanks!

**Comment by lazyfrosch** [comment]
merged in #12
