### ISSUE TITLE
libmysql_shim and libpgsql_shim missing

### ISSUE THREAD

**Issue by NanoCaiordo** [Icinga/rpm-icinga2#7]
Hello, building the rpm on CentOS 6 fails with:

File not found by glob: /root/rpmbuild/BUILDROOT/icinga2-2.8.1-1.el6.x86_64/usr/lib64/icinga2/libmysql_shim*
File not found by glob: /root/rpmbuild/BUILDROOT/icinga2-2.8.1-1.el6.x86_64/usr/lib64/icinga2/libpgsql_shim*

**Comment by dnsmichi** [comment]
Don't use git master, but the release branch.
